ActivosFijo/Controllers/TblMovimientoesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Dynamic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ActivosFijo.Models;
using Mayur.Web.Attributes;
using PagedList;
using System.Web.WebPages;

namespace ActivosFijo.Controllers
{
    [SessionTimeout]
    public class TblMovimientoesController : Controller
    {
        private ActivosFijosEntities db = new ActivosFijosEntities();

        // GET: TblMovimientoes
        public ActionResult Index(string currentFilter, string busqueda, int? page, string name)
        {
            if (busqueda != null)
            {
                page = 1;
            }
            else
            {
                busqueda = currentFilter;
            }

            ViewBag.CurrentFilter = busqueda;

            if (!String.IsNullOrEmpty(busqueda) || !String.IsNullOrEmpty(name) || page > 1)
            {
                var tblActivoes = db.TblActivoes.Include(t => t.TblCategoria).Include(t => t.TblLocacione).Include(t => t.TblOrigene).Include(t => t.TblTiposActivo).Include(t => t.TblPersona);

                if (busqueda.IsInt())
                {
                    int id = Convert.ToInt32(busqueda);
                    tblActivoes = tblActivoes.Where(buscar => buscar.Id == id || buscar.codigoBN.Contains(busqueda) || buscar.codigoOrigen.Contains(busqueda) || buscar.cNoSerial.Contains(busqueda));
                }
                else if (busqueda.IsDateTime())
                {
                    busqueda = Convert.ToDateTime(busqueda).ToString("yyyy-dd-MM");
                    DateTime fechaActivo = Convert.ToDateTime(busqueda);
                    tblActivoes = tblActivoes.Where(buscar => DbFunctions.TruncateTime(buscar.dFechaActivo) == fechaActivo);
                }
                else if (!String.IsNullOrEmpty(busqueda))
                {
                    tblActivoes = tblActivoes.Where(buscar => buscar.cDescripcion.Contains(busqueda) || buscar.cMarca.Contains(busqueda) || buscar.cModelo.Contains(busqueda)
                                                                || buscar.cNoSerial.Contains(busqueda) || buscar.codigoOrigen.Contains(busqueda) || buscar.codigoBN.Contains(busqueda)
                                                                || buscar.TblCategoria.cDescripcion.Contains(busqueda) || buscar.TblOrigene.cDescripcion.Contains(busqueda)
                                                                || buscar.TblLocacione.cDescripcion.Contains(busqueda) || buscar.cAsignacion.Contains(busqueda));
                }

                int pageSize = 20;
                int pageNumber = (page ?? 1);
                //return View(tblActivoes.ToPagedList(pageNumber, pageSize));
                return View(tblActivoes.ToList().ToPagedList(pageNumber, pageSize));
            }
            else
            {
                return View();
            }
        }

        // GET: TblMovimientoes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TblMovimiento tblMovimiento = db.TblMovimientos.Find(id);
            if (tblMovimiento == null)
            {
                return HttpNotFound();
            }
            return View(tblMovimiento);
        }

        // GET: TblMovimientoes/Details/5
        public ActionResult AsignarPersona(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TblActivo tblActivo = db.TblActivoes.Find(id);
            if (tblActivo == null)
            {
                return HttpNotFound();
            }
            ViewBag.IdPersona = new SelectList(db.TblPersonas, "Id", "cNombre", tblActivo.IdPersona);
            return View(tblActivo);
            //return View();
        }

        [HttpPost, ActionName("AsignarPersona")]
        public ActionResult AsignarPersonapost(int? id, string cAsignacion, int? IdPersona, DateTime? fechamovimiento, string usuario, string IdLocacion)
        {
            TblActivo tblActivo = db.TblActivoes.Find(id);
            string[] valores = new string[] { "cAsignacion", "IdPersona" };

            if (TryUpdateModel(tblActivo, valores))
            {
                try
                {
                    db.SaveChanges(); 
                    TempData["Message"] = "Formulario fue editado con exito!";
                    return RedirectToAction("Index");
                }
                catch (Exception e)
                {
                    TempData["Message"] = "Oops, Algo salió mal!";
                }
            }

            ViewBag.IdPersona = new SelectList(db.TblPersonas, "Id", "cNombre", tblActivo.IdPersona);
            return View(tblActivo);
        }

        public ActionResult AsignarLocacion(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TblActivo tblActivo = db.TblActivoes.Find(id);
            if (tblActivo == null)
            {
                return HttpNotFound();
            }
            ViewBag.IdLocacion = new SelectList(db.TblLocaciones, "Id", "cDescripcion", tblActivo.IdLocacion);
            return View(tblActivo);
            //return View();
        }

        [HttpPost]
        public ActionResult AsignarLocacion(int? id, int IdLocacion)
        {
            TblActivo tblActivo = db.TblActivoes.Find(id);
            string[] valores = new string[] { "IdLocacion" };

            if (TryUpdateModel(tblActivo, valores))
            {
                try
                {
                    db.SaveChanges();
                    TempData["Message"] = "Formulario fue editado con exito!";
                    return RedirectToAction("Index");
                }
                catch (Exception e)
                {
                    TempData["Message"] = "Oops, Algo salió mal!";
                }
            }
            ViewBag.IdLocacion = new SelectList(db.TblLocaciones, "Id", "cDescripcion", tblActivo.IdLocacion);
            return View(tblActivo);
            //return View();
        }

        public ActionResult AsignarCategoria(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TblActivo tblActivo = db.TblActivoes.Find(id);
            if (tblActivo == null)
            {
                return HttpNotFound();
            }
            ViewBag.IdCategoria = new SelectList(db.TblCategorias, "Id", "cDescripcion", tblActivo.IdCategoria);
            return View(tblActivo);
            //return View();
        }

        [HttpPost]
        public ActionResult AsignarCategoria(int? id, int IdCategoria)
        {
            TblActivo tblActivo = db.TblActivoes.Find(id);
            string[] valores = new string[] { "IdCategoria" };

            if (TryUpdateModel(tblActivo, valores))
            {
                try
                {
                    db.SaveChanges();
                    TempData["Message"] = "Formulario fue editado con exito!";
                    return RedirectToAction("Index");
                }
                catch (Exception e)
                {
                    TempData["Message"] = "Oops, Algo salió mal!";
                }
            }
            ViewBag.IdCategoria = new SelectList(db.TblCategorias, "Id", "cDescripcion", tblActivo.IdCategoria);
            return View(tblActivo);
            //return View();
        }

        public ActionResult DebajaalActivo(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TblActivo tblActivo = db.TblActivoes.Find(id);
            if (tblActivo == null)
            {
                return HttpNotFound();
            }
            return View(tblActivo);
            //return View();
        }

        [HttpPost]
        public ActionResult DebajaalActivo(int? id, int cEstatus)
        {
            TblActivo tblActivo = db.TblActivoes.Find(id);
            string[] valores = new string[] { "cEstatus" };

            if (TryUpdateModel(tblActivo, valores))
            {
                try
                {
                    db.SaveChanges();
                    TempData["Message"] = "Formulario fue editado con exito!";
                    return RedirectToAction("Index");
                }
                catch (Exception e)
                {
                    TempData["Message"] = "Oops, Algo salió mal!";
                }
            }
            return View(tblActivo);
            //return View();
        }
        // GET: TblMovimientoes/Create
        public ActionResult Create()
        {
            ViewBag.IdCategoria = new SelectList(db.TblCategorias, "Id", "cDescripcion");
            ViewBag.IdLocacion = new SelectList(db.TblLocaciones, "Id", "cDescripcion");
            ViewBag.IdTipoBaja = new SelectList(db.TblTipoBajas, "Id", "cDescripcion");
            ViewBag.IdTipoActivo = new SelectList(db.TblTiposActivos, "Id", "cDescripcion");
            ViewBag.IdPersona = new SelectList(db.TblPersonas, "Id", "cDocumento");
            return View();
        }

        // POST: TblMovimientoes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]

ActivosFijo/Views/TblMovimientoes/Create.cshtml
@model ActivosFijo.Models.TblMovimiento

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>TblMovimiento</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.nTipo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nTipo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nTipo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.cDescripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.cDescripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.cDescripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.dFechaMovimiento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dFechaMovimiento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.dFechaMovimiento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.nMontoMovimiento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nMontoMovimiento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nMontoMovimiento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.dFechaRegistro, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dFechaRegistro, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.dFechaRegistro, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.cUsuario, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.cUsuario, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.cUsuario, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdActivo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IdActivo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IdActivo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.cAsignacion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.cAsignacion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.cAsignacion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdLocacion, "IdLocacion", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdLocacion", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdLocacion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdTipoActivo, "IdTipoActivo", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdTipoActivo", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdTipoActivo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdTipoBaja, "IdTipoBaja", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdTipoBaja", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdTipoBaja, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdCategoria, "IdCategoria", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdCategoria", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdCategoria, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdPersona, "IdPersona", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdPersona", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdPersona, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ActivosFijo/Views/TblMovimientoes/Delete.cshtml
@model ActivosFijo.Models.TblMovimiento

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>TblMovimiento</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.nTipo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nTipo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.cDescripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cDescripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dFechaMovimiento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dFechaMovimiento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.nMontoMovimiento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nMontoMovimiento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dFechaRegistro)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dFechaRegistro)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.cUsuario)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cUsuario)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IdActivo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IdActivo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.cAsignacion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cAsignacion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TblCategoria.cDescripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TblCategoria.cDescripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TblLocacione.cDescripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TblLocacione.cDescripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TblTipoBaja.cDescripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TblTipoBaja.cDescripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TblTiposActivo.cDescripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TblTiposActivo.cDescripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TblPersona.cDocumento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TblPersona.cDocumento)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ActivosFijo/Views/TblMovimientoes/Index.cshtml
@model IEnumerable<ActivosFijo.Models.TblActivo>

@{
    ViewBag.Title = "Index";
}


<div class="row mt-5">
    <div class="col-xl-12">
        <div class="card">
            <div class="card-header border-0">
                <div class="row align-items-center">
                    <div class="col">
                        <h1 class="mb-0">Lista de Activos</h1>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row mt-2">
    <div class="col-xl-12">
        <div class="card">
            <div class="card-header border-0">
                <div class="row align-items-center">
                    <div class="col">
                        <form class="navbar-search navbar-search-light form-inline mr-sm-3" id="navbar-search-main" action="@Url.Action("Index", @ViewContext.RouteData.Values["controller"].ToString())" method="get">
                            <div class="form-group mb-0">
                                <div class="input-group input-group-alternative input-group-merge">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text"><i class="fas fa-search"></i></span>
                                    </div>
                                    <input class="form-control" placeholder="Búscar activo" type="text" value="@(ViewBag.CurrentFilter ?? String.Empty)" name="busqueda" id="busqueda">
                                </div>
                            </div>
                            <button type="button" class="close" data-action="search-close" data-target="#navbar-search-main" aria-label="Close">
                                <span aria-hidden="true">×</span>
                            </button>
                        </form>
                    </div>
                </div>
            </div>
            @*para validar que haya datos en el Model para mostrar los datos en una table*@
            @if (Model != null)
            {
                <div class="table-responsive">
                    @*Table de informacion*@
                    <table class="table align-items-center table-flush">
                        <thead class="thead-light">
                            <tr>
                                <th scope="col">
                                    Acción
                                </th>
                                <th scope="col">
                                    @Html.DisplayNameFor(model => model.First().Id)
                                </th>
                                <th scope="col">
                                    @Html.DisplayNameFor(model => model.First().cDescripcion)
                                </th>
                                <th scope="col">
                                    @Html.DisplayNameFor(model => model.First().cMarca)
                                </th>
                                <th scope="col">
                                    @Html.DisplayNameFor(model => model.First().cModelo)
                                </th>
                                <th scope="col">
                                    @Html.DisplayNameFor(model => model.First().cNoSerial)
                                </th>
                                <th scope="col">
                                    @Html.DisplayNameFor(model => model.First().codigoOrigen)
                                </th>
                                <th scope="col">
                                    @Html.DisplayNameFor(model => model.First().codigoBN)
                                </th>
                                <th scope="col">
                                    @Html.DisplayNameFor(model => model.First().TblCategoria.cDescripcion)
                                </th>
                                <th scope="col">
                                    @Html.DisplayNameFor(model => model.First().TblOrigene.cDescripcion)
                                </th>
                                <th scope="col">
                                    @Html.DisplayNameFor(model => model.First().TblLocacione.cDescripcion)
                                </th>
                                <th scope="col">
                                    @Html.DisplayNameFor(model => model.First().dFechaActivo)
                                </th>
                                <th scope="col">
                                    @Html.DisplayNameFor(model => model.First().cAsignacion)
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            @if (Model != null)
                            {
                                foreach (var item in Model)
                                {
                                    <tr>
                                        <td>
                                            <a href="@Url.Action("AsignarPersona","TblMovimientoes", new { id = item.Id })" title="Asignar a persona">
                                                <i class="fa fa-code-branch text-success" style="font-size: large"></i>
                                            </a>
                                            <a href="@Url.Action("AsignarLocacion","TblMovimientoes", new { id = item.Id })" title="Asignar Locación">
                                                <i class="ni ni-pin-3 text-info" style="font-size: large"></i>
                                            </a>
                                            <a href="@Url.Action("AsignarCategoria","TblMovimientoes", new { id = item.Id })" title="Asignar Categoria">
                                                <i class="ni ni-tag text-primary mh-100" style="font-size: large"></i>
                                            </a>
                                            <a href="@Url.Action("DebajaalActivo","TblMovimientoes", new { id = item.Id })" title="Darle de baja al Activo">
                                                <i class="fa fa-minus-circle text-danger mh-100" style="font-size: large"></i>
                                            </a>
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Id)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.cDescripcion)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.cMarca)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.cModelo)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.cNoSerial)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.codigoOrigen)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.codigoBN)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.TblCategoria.cDescripcion)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.TblOrigene.cDescripcion)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.TblLocacione.cDescripcion)
                                        </td>
                                        <td>
                                            @Convert.ToString(string.Format("{0:dd/MM/yyyy}", item.dFechaActivo))
                                            @*@Html.DisplayFor(modelItem => item.dFechaActivo)*@
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.cAsignacion)
                                        </td>
                                    </tr>
                                }
                            }
                        </tbody>
                    </table>
                </div>
                <div class="row">
                    <div class="col ml-3">
                        @*Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber ) of @Model.PageCount
                        @Html.PagedListPager(Model, page => Url.Action("Index", new { page, currentFilter = ViewBag.CurrentFilter }))*@
                    </div>
                </div>
            }
        </div>
    </div>
</div>

@* Aqui arriba esta un duplicado de los activos *@
<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        @*<th>
            @Html.DisplayNameFor(model => model.nTipo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.cDescripcion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.dFechaMovimiento)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.nMontoMovimiento)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.dFechaRegistro)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.cUsuario)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IdActivo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.cAsignacion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TblCategoria.cDescripcion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TblLocacione.cDescripcion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TblTipoBaja.cDescripcion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TblTiposActivo.cDescripcion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TblPersona.cDocumento)
        </th>*@
        <th></th>
    </tr>

    @*@foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.nTipo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.cDescripcion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.dFechaMovimiento)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.nMontoMovimiento)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.dFechaRegistro)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.cUsuario)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IdActivo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.cAsignacion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TblCategoria.cDescripcion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TblLocacione.cDescripcion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TblTipoBaja.cDescripcion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TblTiposActivo.cDescripcion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TblPersona.cDocumento)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }*@

</table>