ActivosFijo/Models/TblOrigene.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActivosFijo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblOrigene
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblOrigene()
        {
            this.TblActivoes = new HashSet<TblActivo>();
        }
    
        public int Id { get; set; }
        public string cDescripcion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblActivo> TblActivoes { get; set; }
    }
}

ActivosFijo/Controllers/TblOrigenesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ActivosFijo.Models;
using Mayur.Web.Attributes;

namespace ActivosFijo.Controllers
{
    [SessionTimeout]
    public class TblOrigenesController : Controller
    {
        private ActivosFijosEntities db = new ActivosFijosEntities();

        // GET: TblOrigenes
        public ActionResult Index()
        {
            return View(db.TblOrigenes.ToList());
        }

        // GET: TblOrigenes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TblOrigene tblOrigene = db.TblOrigenes.Find(id);
            if (tblOrigene == null)
            {
                return HttpNotFound();
            }
            return View(tblOrigene);
        }

        // GET: TblOrigenes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: TblOrigenes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,cDescripcion")] TblOrigene tblOrigene)
        {
            if (ModelState.IsValid)
            {
                db.TblOrigenes.Add(tblOrigene);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tblOrigene);
        }

        // GET: TblOrigenes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TblOrigene tblOrigene = db.TblOrigenes.Find(id);
            if (tblOrigene == null)
            {
                return HttpNotFound();
            }
            return View(tblOrigene);
        }

        // POST: TblOrigenes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,cDescripcion")] TblOrigene tblOrigene)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tblOrigene).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tblOrigene);
        }

        // GET: TblOrigenes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TblOrigene tblOrigene = db.TblOrigenes.Find(id);
            if (tblOrigene == null)
            {
                return HttpNotFound();
            }
            return View(tblOrigene);
        }

        // POST: TblOrigenes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            TblOrigene tblOrigene = db.TblOrigenes.Find(id);
            db.TblOrigenes.Remove(tblOrigene);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ActivosFijo/Views/TblOrigenes/Create.cshtml
@model ActivosFijo.Models.TblOrigene

@{
    ViewBag.Title = "Create";
}

<div class="container-fluid mt-lg-5">
    <div class="row">
        <div class="col-xl-12 order-xl-">
            <div class="card">
                <div class="card-header">
                    <div class="row align-items-center">
                        <div class="col-8">
                            <h2 class="mb-0">Registrar Origen</h2>
                        </div>
                        <div class="col-4 text-right">
                            <a class="nav-link active" href="@Url.Action("Index","TblOrigenes")">
                                <i class="ni ni-bold-left text-primary"></i>
                                <span class="text-primary">Regresar</span>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                        <h6 class="heading-small text-muted mb-4">Información de la Ubicación</h6>
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="pl-lg-4">
                            <div class="row">
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        @Html.LabelFor(model => model.cDescripcion, htmlAttributes: new { @class = "control-label col-md-12" })
                                        <div class="col-md-12">
                                            @Html.EditorFor(model => model.cDescripcion, new { htmlAttributes = new { @class = "form-control" } })
                                            @Html.ValidationMessageFor(model => model.cDescripcion, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <hr class="my-4" />
                            <div class="row">
                                <div class="col-lg-12">
                                    <div class="form-group">
                                        <div class="col-md-offset-2 col-md-10">
                                            <input type="submit" value="Guardar" class="btn btn-success" />
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

@*<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>TblOrigene</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.cDescripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.cDescripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.cDescripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>*@

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ActivosFijo/Views/TblOrigenes/Delete.cshtml
@model ActivosFijo.Models.TblOrigene

@{
    ViewBag.Title = "Delete";
}

<div class="container-fluid mt-lg-5">
    <div class="row">
        <div class="col-xl-12 order-xl-">
            <div class="card">
                <div class="card-header">
                    <div class="row align-items-center">
                        <div class="col-8">
                            <h2 class="mb-0">Eliminar el Origen</h2>
                        </div>
                        <div class="col-4 text-right">
                            <a class="nav-link active" href="@Url.Action("Index","TblOrigenes")">
                                <i class="ni ni-bold-left text-primary"></i>
                                <span class="text-primary">Regresar</span>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <div class="pl-lg-4">
                        <div class="alert alert-danger" role="alert">
                            <strong>Alerta!</strong> Esta seguro de eliminar este Origen?
                        </div>
                        <div class="row">
                            <div class="col-lg-6">
                                <dl class="dl-horizontal">
                                    <dt>
                                        @Html.DisplayNameFor(model => model.cDescripcion)
                                    </dt>

                                    <dd>
                                        @Html.DisplayFor(model => model.cDescripcion)
                                    </dd>
                                </dl>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-footer">
                    <div class="row align-items-center">

                        <div class="col-12 text-right">
                            @using (Html.BeginForm())
                            {
                                @Html.AntiForgeryToken()

                                <div class="form-actions no-color">
                                    <input type="submit" value="Eliminar" class="btn btn-danger" />
                                </div>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


@*<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>TblOrigene</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.cDescripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cDescripcion)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>*@

ActivosFijo/Views/TblOrigenes/Details.cshtml
@model ActivosFijo.Models.TblOrigene

@{
    ViewBag.Title = "Details";
}

<div class="container-fluid mt-lg-5">
    <div class="row">
        <div class="col-xl-12 order-xl-">
            <div class="card">
                <div class="card-header">
                    <div class="row align-items-center">
                        <div class="col-8">
                            <h2 class="mb-0">Información de Origen</h2>
                        </div>
                        <div class="col-4 text-right">
                            <a class="nav-link active" href="@Url.Action("Index","TblOrigenes")">
                                <i class="ni ni-bold-left text-primary"></i>
                                <span class="text-primary">Regresar</span>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <div class="pl-lg-4">
                        <div class="row">
                            <div class="col-lg-6">
                                <dl class="dl-horizontal">
                                    <dt>
                                        @Html.DisplayNameFor(model => model.cDescripcion)
                                    </dt>

                                    <dd>
                                        @Html.DisplayFor(model => model.cDescripcion)
                                    </dd>
                                </dl>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-footer">
                    <div class="row align-items-center">

                        <div class="col-12 text-right">
                            <a class="btn btn-warning" href="@Url.Action("Edit","TblOrigenes", new { id = Model.Id })">
                                <i class="fa fa-edit"></i>
                                <span>Editar</span>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@*<h2>Details</h2>

<div>
    <h4>TblOrigene</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.cDescripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cDescripcion)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>*@

ActivosFijo/Views/TblOrigenes/Edit.cshtml
@model ActivosFijo.Models.TblOrigene

@{
    ViewBag.Title = "Edit";
}

<div class="container-fluid mt-lg-5">
    <div class="row">
        <div class="col-xl-12 order-xl-">
            <div class="card">
                <div class="card-header">
                    <div class="row align-items-center">
                        <div class="col-8">
                            <h2 class="mb-0">Edición de Origen</h2>
                        </div>
                        <div class="col-4 text-right">
                            <a class="nav-link active" href="@Url.Action("Index","TblOrigenes")">
                                <i class="ni ni-bold-left text-primary"></i>
                                <span class="text-primary">Regresar</span>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()
                        <h6 class="heading-small text-muted mb-4">Información de Origen</h6>
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.Id)
                        <div class="pl-lg-4">
                            <div class="row">
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        @Html.LabelFor(model => model.cDescripcion, htmlAttributes: new { @class = "control-label col-md-12" })
                                        <div class="col-md-12">
                                            @Html.EditorFor(model => model.cDescripcion, new { htmlAttributes = new { @class = "form-control" } })
                                            @Html.ValidationMessageFor(model => model.cDescripcion, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <hr class="my-4" />
                            <div class="row">
                                <div class="col-lg-12">
                                    <div class="form-group">
                                        <div class="col-md-offset-2 col-md-10">
                                            <input type="submit" value="Guardar" class="btn btn-success" />
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

@*<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>TblOrigene</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.cDescripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.cDescripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.cDescripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>*@

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ActivosFijo/Views/TblOrigenes/Index.cshtml
@model IEnumerable<ActivosFijo.Models.TblOrigene>

@{
    ViewBag.Title = "Index";
}

<div class="row mt-5">
    <div class="col-xl-12">
        <div class="card">
            <div class="card-header border-0">
                <div class="row align-items-center">
                    <div class="col">
                        <h3 class="mb-0">Lista de Origenes</h3>
                    </div>
                    <div class="col text-right">
                        <a class="nav-link active" href="@Url.Action("Create","TblOrigenes")">
                            <i class="fa fa-plus-circle text-success"></i>
                        </a>
                    </div>
                </div>
            </div>
            <div class="table-responsive">
                @*Table de informacion*@
                <table class="table align-items-center table-flush">
                    <thead class="thead-light">
                        <tr>
                            <th scope="col">
                                Acción
                            </th>
                            <th scope="col">
                                @Html.DisplayNameFor(model => model.cDescripcion)
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    <div class="row">
                                        <a class="nav-link active" href="@Url.Action("Edit","TblOrigenes", new { id = item.Id })">
                                            <i class="fa fa-edit text-success"></i>
                                        </a>
                                        <a class="nav-link active" href="@Url.Action("Details","TblOrigenes", new { id = item.Id })">
                                            <i class="fa fa-eye text-info"></i>
                                        </a>
                                        <a class="nav-link active" href="@Url.Action("Delete","TblOrigenes", new { id = item.Id })">
                                            <i class="ni ni-fat-remove text-danger mh-100"></i>
                                        </a>
                                    </div>
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.cDescripcion)
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

@*<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.cDescripcion)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.cDescripcion)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>*@