ActivosFijo/Models/TblLocacione.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActivosFijo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblLocacione
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblLocacione()
        {
            this.TblActivoes = new HashSet<TblActivo>();
            this.TblMovimientos = new HashSet<TblMovimiento>();
        }
    
        public int Id { get; set; }
        public string cDescripcion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblActivo> TblActivoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMovimiento> TblMovimientos { get; set; }
    }
}

ActivosFijo/Controllers/TblLocacionesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ActivosFijo.Models;
using Mayur.Web.Attributes;
using PagedList;

namespace ActivosFijo.Controllers
{
    [SessionTimeout]
    public class TblLocacionesController : Controller
    {
        private ActivosFijosEntities db = new ActivosFijosEntities();

        // GET: TblLocaciones
        public ActionResult Index(string busqueda, int? page)
        {
            var tblLocaciones = db.TblLocaciones.AsQueryable();

            if (!String.IsNullOrEmpty(busqueda))
            {
                tblLocaciones = tblLocaciones.Where(buscar => buscar.cDescripcion.Contains(busqueda));
            }

            int pageSize = 20;
            int pageNumber = (page ?? 1);

            return View(tblLocaciones.ToList().ToPagedList(pageNumber, pageSize));
        }

        // GET: TblLocaciones/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TblLocacione tblLocacione = db.TblLocaciones.Find(id);
            if (tblLocacione == null)
            {
                return HttpNotFound();
            }
            return View(tblLocacione);
        }

        // GET: TblLocaciones/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: TblLocaciones/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,cDescripcion")] TblLocacione tblLocacione)
        {
            if (ModelState.IsValid)
            {
                db.TblLocaciones.Add(tblLocacione);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tblLocacione);
        }

        // GET: TblLocaciones/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TblLocacione tblLocacione = db.TblLocaciones.Find(id);
            if (tblLocacione == null)
            {
                return HttpNotFound();
            }
            return View(tblLocacione);
        }

        // POST: TblLocaciones/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,cDescripcion")] TblLocacione tblLocacione)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tblLocacione).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tblLocacione);
        }

        // GET: TblLocaciones/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TblLocacione tblLocacione = db.TblLocaciones.Find(id);
            if (tblLocacione == null)
            {
                return HttpNotFound();
            }
            return View(tblLocacione);
        }

        // POST: TblLocaciones/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            TblLocacione tblLocacione = db.TblLocaciones.Find(id);
            db.TblLocaciones.Remove(tblLocacione);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ActivosFijo/Views/TblLocaciones/Create.cshtml
@model ActivosFijo.Models.TblLocacione

@{
    ViewBag.Title = "Create";
}

<div class="container-fluid mt-lg-5">
    <div class="row">
        <div class="col-xl-12 order-xl-">
            <div class="card">
                <div class="card-header">
                    <div class="row align-items-center">
                        <div class="col-8">
                            <h2 class="mb-0">Registrar Ubicación</h2>
                        </div>
                        <div class="col-4 text-right">
                            <a class="nav-link active" href="@Url.Action("Index","TblLocaciones")">
                                <i class="ni ni-bold-left text-primary"></i>
                                <span class="text-primary">Regresar</span>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                        <h6 class="heading-small text-muted mb-4">Información de la Ubicación</h6>
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="pl-lg-4">
                            <div class="row">
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        @Html.LabelFor(model => model.cDescripcion, htmlAttributes: new { @class = "control-label col-md-12" })
                                        <div class="col-md-12">
                                            @Html.EditorFor(model => model.cDescripcion, new { htmlAttributes = new { @class = "form-control" } })
                                            @Html.ValidationMessageFor(model => model.cDescripcion, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <hr class="my-4" />
                            <div class="row">
                                <div class="col-lg-12">
                                    <div class="form-group">
                                        <div class="col-md-offset-2 col-md-10">
                                            <input type="submit" value="Guardar" class="btn btn-success" />
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>

</div>
@*<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>TblLocacione</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.cDescripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.cDescripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.cDescripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>*@

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ActivosFijo/Views/TblLocaciones/Delete.cshtml
@model ActivosFijo.Models.TblLocacione

@{
    ViewBag.Title = "Delete";
}

<div class="container-fluid mt-lg-5">
    <div class="row">
        <div class="col-xl-12 order-xl-">
            <div class="card">
                <div class="card-header">
                    <div class="row align-items-center">
                        <div class="col-8">
                            <h2 class="mb-0">Eliminar la Ubicación</h2>
                        </div>
                        <div class="col-4 text-right">
                            <a class="nav-link active" href="@Url.Action("Index","TblLocaciones")">
                                <i class="ni ni-bold-left text-primary"></i>
                                <span class="text-primary">Regresar</span>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <div class="pl-lg-4">
                        <div class="alert alert-danger" role="alert">
                            <strong>Alerta!</strong> Esta seguro de eliminar esta Ubicación?
                        </div>
                        <div class="row">
                            <div class="col-lg-6">
                                <dl class="dl-horizontal">
                                    <dt>
                                        @Html.DisplayNameFor(model => model.cDescripcion)
                                    </dt>

                                    <dd>
                                        @Html.DisplayFor(model => model.cDescripcion)
                                    </dd>
                                </dl>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-footer">
                    <div class="row align-items-center">

                        <div class="col-12 text-right">
                            @using (Html.BeginForm())
                            {
                                @Html.AntiForgeryToken()

                                <div class="form-actions no-color">
                                    <input type="submit" value="Eliminar" class="btn btn-danger" />
                                </div>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


@*<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>TblLocacione</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.cDescripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cDescripcion)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>*@

ActivosFijo/Views/TblLocaciones/Details.cshtml
@model ActivosFijo.Models.TblLocacione

@{
    ViewBag.Title = "Details";
}

<div class="container-fluid mt-lg-5">
    <div class="row">
        <div class="col-xl-12 order-xl-">
            <div class="card">
                <div class="card-header">
                    <div class="row align-items-center">
                        <div class="col-8">
                            <h2 class="mb-0">Información de la Ubicación</h2>
                        </div>
                        <div class="col-4 text-right">
                            <a class="nav-link active" href="@Url.Action("Index","TblLocaciones")">
                                <i class="ni ni-bold-left text-primary"></i>
                                <span class="text-primary">Regresar</span>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <div class="pl-lg-4">
                        <div class="row">
                            <div class="col-lg-6">
                                <dl class="dl-horizontal">
                                    <dt>
                                        @Html.DisplayNameFor(model => model.cDescripcion)
                                    </dt>

                                    <dd>
                                        @Html.DisplayFor(model => model.cDescripcion)
                                    </dd>
                                </dl>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-footer">
                    <div class="row align-items-center">

                        <div class="col-12 text-right">
                            <a class="btn btn-warning" href="@Url.Action("Edit","TblLocaciones", new { id = Model.Id })">
                                <i class="fa fa-edit"></i>
                                <span>Editar</span>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@*<h2>Details</h2>

<div>
    <h4>TblLocacione</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.cDescripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cDescripcion)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>*@

ActivosFijo/Views/TblLocaciones/Edit.cshtml
@model ActivosFijo.Models.TblLocacione

@{
    ViewBag.Title = "Edit";
}

<div class="container-fluid mt-lg-5">
    <div class="row">
        <div class="col-xl-12 order-xl-">
            <div class="card">
                <div class="card-header">
                    <div class="row align-items-center">
                        <div class="col-8">
                            <h2 class="mb-0">Edición de Ubicación</h2>
                        </div>
                        <div class="col-4 text-right">
                            <a class="nav-link active" href="@Url.Action("Index","TblLocaciones")">
                                <i class="ni ni-bold-left text-primary"></i>
                                <span class="text-primary">Regresar</span>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()
                        <h6 class="heading-small text-muted mb-4">Información de la Ubicación</h6>
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.Id)
                        <div class="pl-lg-4">
                            <div class="row">
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        @Html.LabelFor(model => model.cDescripcion, htmlAttributes: new { @class = "control-label col-md-12" })
                                        <div class="col-md-12">
                                            @Html.EditorFor(model => model.cDescripcion, new { htmlAttributes = new { @class = "form-control" } })
                                            @Html.ValidationMessageFor(model => model.cDescripcion, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <hr class="my-4" />
                            <div class="row">
                                <div class="col-lg-12">
                                    <div class="form-group">
                                        <div class="col-md-offset-2 col-md-10">
                                            <input type="submit" value="Guardar" class="btn btn-success" />
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

@*<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>TblLocacione</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.cDescripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.cDescripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.cDescripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>*@

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ActivosFijo/Views/TblLocaciones/Index.cshtml
@model PagedList.IPagedList<ActivosFijo.Models.TblLocacione>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Index";
}

<div class="row mt-5">
    <div class="col-xl-12">
        <div class="card">
            <div class="card-header border-0">
                <div class="row align-items-center">
                    <div class="col">
                        <h3 class="mb-0">Lista de Ubicaciones</h3>
                    </div>
                    <form class="navbar-search navbar-search-light form-inline mr-sm-3" id="navbar-search-main" action="@Url.Action("Index", @ViewContext.RouteData.Values["controller"].ToString())" method="get">
                        <div class="form-group mb-0">
                            <div class="input-group input-group-alternative input-group-merge">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fas fa-search"></i></span>
                                </div>
                                <input class="form-control" placeholder="Búscar locacion" type="text" value="@(ViewBag.CurrentFilter ?? String.Empty)" name="busqueda">
                            </div>
                        </div>
                        <button type="button" class="close" data-action="search-close" data-target="#navbar-search-main" aria-label="Close">
                            <span aria-hidden="true">×</span>
                        </button>
                    </form>
                    <div class="col text-right">
                        <a class="nav-link active" href="@Url.Action("Create","TblLocaciones")">
                            <i class="fa fa-plus-circle text-success"></i>
                        </a>
                    </div>
                </div>
            </div>
            <div class="table-responsive">
                @*Table de informacion*@
                <table class="table align-items-center table-flush">
                    <thead class="thead-light">
                        <tr>
                            <th scope="col">
                                Acción
                            </th>
                            <th scope="col">
                                @Html.DisplayNameFor(model => model.First().cDescripcion)
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    <div class="row">
                                        <a class="nav-link active" href="@Url.Action("Edit","TblLocaciones", new { id = item.Id })">
                                            <i class="fa fa-edit text-success"></i>
                                        </a>
                                        <a class="nav-link active" href="@Url.Action("Details","TblLocaciones", new { id = item.Id })">
                                            <i class="fa fa-eye text-info"></i>
                                        </a>
                                        <a class="nav-link active" href="@Url.Action("Delete","TblLocaciones", new { id = item.Id })">
                                            <i class="ni ni-fat-remove text-danger mh-100"></i>
                                        </a>
                                    </div>
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.cDescripcion)
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            <div class="row">
                <div class="col ml-3">
                    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
                    @Html.PagedListPager(Model, page => Url.Action("Index", new { page, currentFilter = ViewBag.CurrentFilter }))
                </div>
            </div>
        </div>
    </div>
</div>

@*<h2>Index</h2>

    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.cDescripcion)
            </th>
            <th></th>
        </tr>

    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.cDescripcion)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
                @Html.ActionLink("Details", "Details", new { id=item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id=item.Id })
            </td>
        </tr>
    }

    </table>*@