ActivosFijo/Models/TblPersona.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActivosFijo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblPersona
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblPersona()
        {
            this.TblActivoes = new HashSet<TblActivo>();
            this.TblMovimientos = new HashSet<TblMovimiento>();
        }
    
        public int Id { get; set; }
        public string cDocumento { get; set; }
        public string cNombre { get; set; }
        public string cApellido { get; set; }
        public string cSexo { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public string Correo { get; set; }
        public Nullable<int> IdPlan { get; set; }
        public string RegistradoPor { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public Nullable<int> provinciaid { get; set; }
        public string provincia { get; set; }
        public Nullable<int> municipioid { get; set; }
        public string municipio { get; set; }
        public string telefono { get; set; }
        public string Cargo { get; set; }
    
        public virtual Municipio Municipio1 { get; set; }
        public virtual Plane Plane { get; set; }
        public virtual Provincia Provincia1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblActivo> TblActivoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMovimiento> TblMovimientos { get; set; }
    }
}

ActivosFijo/Controllers/TblPersonasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ActivosFijo.Models;
using Mayur.Web.Attributes;
using PagedList;
using System.Configuration;
using Microsoft.Reporting.WebForms;

namespace ActivosFijo.Controllers
{
    [SessionTimeout]
    public class TblPersonasController : Controller
    {
        private ActivosFijosEntities db = new ActivosFijosEntities();

        // GET: TblPersonas
        public ActionResult Index(string busqueda, int? page)
        {

            var tblPersonas = db.TblPersonas.AsQueryable();

            if (!String.IsNullOrEmpty(busqueda))
            {
                tblPersonas = tblPersonas.Where(buscar => buscar.cNombre.Contains(busqueda));
            }

            int pageSize = 20;
            int pageNumber = (page ?? 1);

            return View(tblPersonas.ToList().ToPagedList(pageNumber, pageSize));
        }

        // GET: TblPersonas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TblPersona tblPersona = db.TblPersonas.Find(id);
            if (tblPersona == null)
            {
                return HttpNotFound();
            }
            return View(tblPersona);
        }

        // GET: TblPersonas/Create
        public ActionResult Create()
        {
            ViewBag.municipioid = new SelectList(db.Municipios, "Id", "Nombre");
            ViewBag.IdPlan = new SelectList(db.Planes, "Id", "Plan");
            ViewBag.provinciaid = new SelectList(db.Provincias, "Id", "Nombre");
            return View();
        }

        // POST: TblPersonas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,cDocumento,cNombre,cApellido,cSexo,FechaNacimiento,Correo,IdPlan,RegistradoPor,FechaRegistro,provinciaid,provincia,municipioid,municipio,telefono,Cargo")] TblPersona tblPersona)
        {
            if (ModelState.IsValid)
            {
                db.TblPersonas.Add(tblPersona);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.municipioid = new SelectList(db.Municipios, "Id", "MunicipioId", tblPersona.municipioid);
            ViewBag.IdPlan = new SelectList(db.Planes, "Id", "Plan", tblPersona.IdPlan);
            ViewBag.provinciaid = new SelectList(db.Provincias, "Id", "ProvinciaId", tblPersona.provinciaid);
            return View(tblPersona);
        }

        // GET: TblPersonas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TblPersona tblPersona = db.TblPersonas.Find(id);
            if (tblPersona == null)
            {
                return HttpNotFound();
            }
            ViewBag.municipioid = new SelectList(db.Municipios, "Id", "MunicipioId", tblPersona.municipioid);
            ViewBag.IdPlan = new SelectList(db.Planes, "Id", "Plan", tblPersona.IdPlan);
            ViewBag.provinciaid = new SelectList(db.Provincias, "Id", "ProvinciaId", tblPersona.provinciaid);
            return View(tblPersona);
        }

        // POST: TblPersonas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,cDocumento,cNombre,cApellido,cSexo,FechaNacimiento,Correo,IdPlan,RegistradoPor,FechaRegistro,provinciaid,provincia,municipioid,municipio,telefono,Cargo")] TblPersona tblPersona)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tblPersona).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.municipioid = new SelectList(db.Municipios, "Id", "MunicipioId", tblPersona.municipioid);
            ViewBag.IdPlan = new SelectList(db.Planes, "Id", "Plan", tblPersona.IdPlan);
            ViewBag.provinciaid = new SelectList(db.Provincias, "Id", "ProvinciaId", tblPersona.provinciaid);
            return View(tblPersona);
        }

        // GET: TblPersonas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TblPersona tblPersona = db.TblPersonas.Find(id);
            if (tblPersona == null)
            {
                return HttpNotFound();
            }
            return View(tblPersona);
        }

        // POST: TblPersonas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            TblPersona tblPersona = db.TblPersonas.Find(id);
            db.TblPersonas.Remove(tblPersona);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Report()
        {
            string usuario = ConfigurationManager.AppSettings["ReportServerUser"];
            string clave = ConfigurationManager.AppSettings["ReportServerPassword"];
            string reportServerUrl = ConfigurationManager.AppSettings["ReportServerUrl"];
            Microsoft.Reporting.WebForms.ReportViewer viewer = new Microsoft.Reporting.WebForms.ReportViewer();
            viewer.ProcessingMode = Microsoft.Reporting.WebForms.ProcessingMode.Remote;
            viewer.SizeToReportContent = true;
            viewer.AsyncRendering = true;
            viewer.ServerReport.ReportServerUrl = new Uri(reportServerUrl);
            viewer.ServerReport.ReportPath = "/report/ActivoFijo/rptActaEntregaActivosFijos";
            viewer.ServerReport.ReportServerCredentials = new Microsoft.Reporting.WebForms.ReportServerCredentials(usuario, clave, "http://13.65.93.192/Reports");

            List<ReportParameter> _listPrmNoSolicitud = new List<ReportParameter>();
            ReportParameter prmNoSolicitud = new ReportParameter();
            prmNoSolicitud.Name = "AsignadoA";
            prmNoSolicitud.Values.Add("ABDIAS ROSARIO");
            _listPrmNoSolicitud.Add(prmNoSolicitud);
            //viewer.ServerReport.SetParameters(_listPrmNoSolicitud);
            ViewBag.ReportViewer = viewer;
            /*
            CustomReportCredentials credenciales = new CustomReportCredentials(usuario, clave, reportDomain);
            string serverURL = "http://13.65.93.192/Reports/";
            string reportPath = "";

            Reporter reporter = new Reporter(viewer, serverURL, reportPath, credenciales);

           

            reporter.SetParametros(valoresReporteParametro);
            

            ViewBag.ReportViewer = reporter.GetReportViewer();*/


            return View();
        }

        public class Reporter
        {
            private ReportViewer _report = null;
            List<ReportParameter> _listPrmNoSolicitud = null;
            public Reporter(ReportViewer report, string serverURL, string reportPath, CustomReportCredentials customerReportCredentials)
            {
                _report = report;
                _report.ProcessingMode = ProcessingMode.Remote;
                IReportServerCredentials irsc = customerReportCredentials;
                _report.ServerReport.ReportServerCredentials = irsc;
                _report.ServerReport.ReportServerUrl = new Uri(serverURL);
                _report.ServerReport.ReportPath = reportPath;
            }

            public void SetParametros(Dictionary<string, List<string>> parametros)
            {


                _listPrmNoSolicitud = new List<ReportParameter>();

                foreach (string k in parametros.Keys)
                {
                    ReportParameter prmNoSolicitud = new ReportParameter();
                    prmNoSolicitud.Name = k;
                    foreach (string v in parametros[k])
                    {
                        prmNoSolicitud.Values.Add(v);
                    }

                    _listPrmNoSolicitud.Add(prmNoSolicitud);
                }

                _report.ServerReport.SetParameters(_listPrmNoSolicitud);
            }


            public void RunReport()
            {
                _report.ServerReport.Refresh();
                _report.DataBind();
                _report.Focus();


            }

            public ReportViewer GetReportViewer()
            { 
                return _report;
            }
        }

        public class CustomReportCredentials : IReportServerCredentials
        {
            private string _UserName;
            private string _PassWord;
            private string _DomainName;

            public CustomReportCredentials(string UserName, string PassWord, string DomainName)
            {
                _UserName = UserName;
                _PassWord = PassWord;
                _DomainName = DomainName;
            }

            public System.Security.Principal.WindowsIdentity ImpersonationUser
            {
                get { return null; }
            }

            public ICredentials NetworkCredentials
            {
                get { return new NetworkCredential(_UserName, _PassWord, _DomainName); }
            }

            public bool GetFormsCredentials(out Cookie authCookie, out string user,
             out string password, out string authority)
            {

ActivosFijo/Views/TblPersonas/Delete.cshtml
@model ActivosFijo.Models.TblPersona

@{
    ViewBag.Title = "Delete";
}


<div class="container-fluid mt-lg-5">
    <div class="row">
        <div class="col-xl-12 order-xl-">
            <div class="card">
                <div class="card-header">
                    <div class="row align-items-center">
                        <div class="col-8">
                            <h2 class="mb-0">Eliminar Persona</h2>
                        </div>
                        <div class="col-4 text-right">
                            <a class="nav-link active" href="@Url.Action("Index","TblPersonas")">
                                <i class="ni ni-bold-left text-primary"></i>
                                <span class="text-primary">Regresar</span>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <div class="pl-lg-4">
                        <div class="alert alert-danger" role="alert">
                            <strong>Alerta!</strong> Esta seguro de eliminar esta Persona?
                        </div>
                        <div class="row">
                            <div class="col-lg-4">
                                <dl class="dl-horizontal">
                                    <dt>
                                        @Html.DisplayNameFor(model => model.cDocumento)
                                    </dt>

                                    <dd>
                                        @Html.DisplayFor(model => model.cDocumento)
                                    </dd>
                                </dl>
                            </div>
                            <div class="col-lg-4">
                                <dl class="dl-horizontal">
                                    <dt>
                                        @Html.DisplayNameFor(model => model.cNombre)
                                    </dt>

                                    <dd>
                                        @Html.DisplayFor(model => model.cNombre)
                                    </dd>
                                </dl>
                            </div>
                            <div class="col-lg-4">
                                <dl class="dl-horizontal">
                                    <dt>
                                        @Html.DisplayNameFor(model => model.cApellido)
                                    </dt>

                                    <dd>
                                        @Html.DisplayFor(model => model.cApellido)
                                    </dd>
                                </dl>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-4">
                                <dl class="dl-horizontal">
                                    <dt>
                                        @Html.DisplayNameFor(model => model.cSexo)
                                    </dt>

                                    <dd>
                                        @Html.DisplayFor(model => model.cSexo)
                                    </dd>
                                </dl>
                            </div>
                            <div class="col-lg-4">
                                <dl class="dl-horizontal">

                                    <dt>
                                        @Html.DisplayNameFor(model => model.FechaNacimiento)
                                    </dt>

                                    <dd>
                                        @Html.DisplayFor(model => model.FechaNacimiento)
                                    </dd>
                                </dl>
                            </div>
                            <div class="col-lg-4">
                                <dl class="dl-horizontal">
                                    <dt>
                                        @Html.DisplayNameFor(model => model.Correo)
                                    </dt>

                                    <dd>
                                        @Html.DisplayFor(model => model.Correo)
                                    </dd>
                                </dl>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-4">
                                <dl class="dl-horizontal">
                                    <dt>
                                        @Html.DisplayNameFor(model => model.RegistradoPor)
                                    </dt>

                                    <dd>
                                        @Html.DisplayFor(model => model.RegistradoPor)
                                    </dd>
                                </dl>
                            </div>
                            <div class="col-lg-4">
                                <dl class="dl-horizontal">
                                    <dt>
                                        @Html.DisplayNameFor(model => model.FechaRegistro)
                                    </dt>

                                    <dd>
                                        @Html.DisplayFor(model => model.FechaRegistro)
                                    </dd>
                                </dl>
                            </div>
                            <div class="col-lg-4">
                                <dl class="dl-horizontal">
                                    <dt>
                                        @Html.DisplayNameFor(model => model.provincia)
                                    </dt>

                                    <dd>
                                        @Html.DisplayFor(model => model.provincia)
                                    </dd>
                                </dl>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-4">
                                <dl class="dl-horizontal">
                                    <dt>
                                        @Html.DisplayNameFor(model => model.municipio)
                                    </dt>

                                    <dd>
                                        @Html.DisplayFor(model => model.municipio)
                                    </dd>
                                </dl>
                            </div>
                            <div class="col-lg-4">
                                <dl class="dl-horizontal">
                                    <dt>
                                        @Html.DisplayNameFor(model => model.telefono)
                                    </dt>

                                    <dd>
                                        @Html.DisplayFor(model => model.telefono)
                                    </dd>
                                </dl>
                            </div>
                            <div class="col-lg-4">
                                <dl class="dl-horizontal">
                                    <dt>
                                        @Html.DisplayNameFor(model => model.Cargo)
                                    </dt>

                                    <dd>
                                        @Html.DisplayFor(model => model.Cargo)
                                    </dd>
                                </dl>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-4">
                                <dl class="dl-horizontal">
                                    <dt>
                                        @Html.DisplayNameFor(model => model.Municipio1.MunicipioId)
                                    </dt>

                                    <dd>
                                        @Html.DisplayFor(model => model.Municipio1.MunicipioId)
                                    </dd>
                                </dl>
                            </div>
                            <div class="col-lg-4">
                                <dl class="dl-horizontal">
                                    <dt>
                                        @Html.DisplayNameFor(model => model.Plane.Plan)
                                    </dt>

                                    <dd>
                                        @Html.DisplayFor(model => model.Plane.Plan)
                                    </dd>
                                </dl>
                            </div>
                            <div class="col-lg-4">
                                <dl class="dl-horizontal">
                                    <dt>
                                        @Html.DisplayNameFor(model => model.Provincia1.ProvinciaId)
                                    </dt>

                                    <dd>
                                        @Html.DisplayFor(model => model.Provincia1.ProvinciaId)
                                    </dd>
                                </dl>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-footer">
                    <div class="row align-items-center">

                        <div class="col-12 text-right">
                            @using (Html.BeginForm())
                            {
                                @Html.AntiForgeryToken()

                                <div class="form-actions no-color">
                                    <input type="submit" value="Eliminar" class="btn btn-danger" />
                                </div>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@*<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>TblPersona</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.cDocumento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cDocumento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.cNombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cNombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.cApellido)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cApellido)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.cSexo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cSexo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaNacimiento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaNacimiento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Correo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Correo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RegistradoPor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RegistradoPor)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaRegistro)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaRegistro)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.provincia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.provincia)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.municipio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.municipio)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.telefono)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.telefono)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cargo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cargo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Municipio1.MunicipioId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Municipio1.MunicipioId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Plane.Plan)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Plane.Plan)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Provincia1.ProvinciaId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Provincia1.ProvinciaId)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>*@

ActivosFijo/Views/TblPersonas/Report.cshtml
@using ReportViewerForMvc


@if (ViewBag.ReportViewer != null)
{
    @Html.ReportViewer(ViewBag.ReportViewer as Microsoft.Reporting.WebForms.ReportViewer)
}